name: dsw_51762
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  very_good_analysis: 6.0.0
  shared_preferences: 2.3.3
  sqflite: 2.0.0+3
  intl: 0.17.0
  path: 1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

